In [2]:
import numpy as np
import pandas as pd
import os
import warnings; warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
os.listdir('../data/raw')

['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [4]:
df = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5204,4282-ACRXS,Male,1,Yes,No,38,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.85,955.75,No
1166,7129-ACFOG,Female,0,No,No,5,Yes,Yes,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,53.80,283.95,No
3300,1403-LKLIK,Female,0,Yes,Yes,33,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.10,579.4,No
6987,5981-ZVXOT,Female,1,No,No,35,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,108.35,3726.15,No
5213,7668-XCFYV,Female,1,Yes,No,17,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,92.55,1614.7,No

In [6]:
df.shape

(7043, 21)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [9]:
df[ df['gender'] == 'Female'].value_counts().sum()

np.int64(3488)

# Gender: Female, Male, Total

In [10]:
female_sum = df['gender'].value_counts()[1]
male_sum = df['gender'].value_counts()[0]
totall_sum = df.shape[0]

print(f'Total Female: {female_sum}')
print(f'Total Male: {male_sum}')
print(f'Total: {totall_sum}')

Total Female: 3488
Total Male: 3555
Total: 7043

In [37]:
df[ df["gender"]== 'Female'].value_counts().sum()

np.int64(3488)

# Partner: No, Yes, Total

In [11]:
Partner_no = df["Partner"].value_counts()[0]
Partner_yes = df["Partner"].value_counts()[1]
Partner_all = df.shape[0]


print(f'Partner NO: {Partner_no}')
print(f'Partner YES: {Partner_yes}')
print(f'Total Partner: {Partner_all}')

Partner NO: 3641
Partner YES: 3402
Total Partner: 7043

# Partner: Yes, no | Gender: Male, Female

In [12]:
partner_yes_male = df[ df['Partner'] == 'Yes'][ df["gender"] == 'Male'].value_counts().sum() 
partner_yes_female = df[ df['Partner'] == 'Yes'][ df["gender"] == 'Female'].value_counts().sum()

partner_no_male = df[ df["Partner"] == 'No'][df['gender'] == 'Male'].value_counts().sum()
partner_no_female = df[ df["Partner"] == 'No'][df['gender'] == 'Female'].value_counts().sum()


print(f'Total Partner = Yes & Male : {partner_yes_male}')
print(f'Total Partner = Yes & Female : {partner_yes_female}')


print(f'Total Partner = No & Male : {partner_no_male}')
print(f'Total Partner = No & Female : {partner_no_female}')

Total Partner = Yes & Male : 1714
Total Partner = Yes & Female : 1688
Total Partner = No & Male : 1841
Total Partner = No & Female : 1800

In [13]:
df.sample(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5302,9700-ISPUP,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,No,Yes,No,Yes,Month-to-month,Yes,Electronic check,65.5,616.9,No
1755,1803-BGNBD,Female,0,No,No,12,Yes,No,DSL,No,...,No,Yes,No,No,Month-to-month,Yes,Electronic check,54.3,654.5,No

# Tenure

In [14]:
sorted_tenure = sorted(df["tenure"].unique().tolist())

print(f'Tenure sorted: {sorted_tenure}')

Tenure sorted: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]

# MultipleLines

In [15]:
MultipleLines_yes = df["MultipleLines"].value_counts()[0]
MultipleLines_no = df["MultipleLines"].value_counts()[1]
MultipleLines_sum = df["MultipleLines"].value_counts().sum()
total_MultipleLines = df["MultipleLines"].value_counts().sum()

print(f'Total MultipleLines Yes: {MultipleLines_yes}')
print(f'Total MultipleLines No: {MultipleLines_no}')
print(f'Total MultipleLines Sum: {MultipleLines_sum}')
print(f'Total MultipleLines: {total_MultipleLines}')

Total MultipleLines Yes: 3390
Total MultipleLines No: 2971
Total MultipleLines Sum: 7043
Total MultipleLines: 7043

# PhoneService

In [16]:
PhoneService_yes = df["PhoneService"].value_counts()[0]
PhoneService_no = df["PhoneService"].value_counts()[1]
PhoneService_sum = df["PhoneService"].value_counts().sum()
total_PhoneService = df["PhoneService"].value_counts().sum()

print(f'Total PhoneService Yes: {PhoneService_yes}')
print(f'Total PhoneService No: {PhoneService_no}')
print(f'Total PhoneService Sum: {PhoneService_sum}')
print(f'Total PhoneService: {total_PhoneService}')

Total PhoneService Yes: 6361
Total PhoneService No: 682
Total PhoneService Sum: 7043
Total PhoneService: 7043

# InternetService

In [17]:
InternetService_Fiber_optic = df["InternetService"].value_counts()[0]
InternetService_DSL = df["InternetService"].value_counts()[1]
InternetService_no = df["InternetService"].value_counts()[2]
total_InternetService = df["InternetService"].value_counts().sum()

print(f'Total InternetService Fiber optic: {InternetService_Fiber_optic}')
print(f'Total InternetService DSL: {InternetService_DSL}')
print(f'Total InternetService No: {InternetService_no}')
print(f'Total InternetService: {total_InternetService}')

Total InternetService Fiber optic: 3096
Total InternetService DSL: 2421
Total InternetService No: 1526
Total InternetService: 7043

# OnlineSecurity

In [19]:

OnlineSecurity_no = df["OnlineSecurity"].value_counts()[0]
OnlineSecurity_yes = df["OnlineSecurity"].value_counts()[1]
OnlineSecurity_no_intert = df["OnlineSecurity"].value_counts()[2]
total_OnlineSecurity = df ["OnlineSecurity"].value_counts().sum()

print(f'Total OnlineSecurity no: {OnlineSecurity_no}')
print(f'Total OnlineSecurity yes: {OnlineSecurity_yes}')
print(f'Total OnlineSecurity no intert: {OnlineSecurity_no_intert}')
print(f'Total OnlineSecurity: {total_OnlineSecurity}')

Total OnlineSecurity no: 3498
Total OnlineSecurity yes: 2019
Total OnlineSecurity no intert: 1526
Total OnlineSecurity: 7043

In [43]:
df[ df["OnlineSecurity"]== 'No internet service'].value_counts().sum()

np.int64(1526)

In [42]:
df["OnlineSecurity"].value_counts()

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

# DeviceProtection

In [20]:
DeviceProtection_no = df["DeviceProtection"].value_counts()[0]
DeviceProtection_yes = df["DeviceProtection"].value_counts()[1]
DeviceProtection_no_intert = df["DeviceProtection"].value_counts()[2]
Total_DeviceProtection = df["DeviceProtection"].value_counts().sum()

print(f'Total DeviceProtection no: {DeviceProtection_no}')
print(f'Total DeviceProtection yes: {DeviceProtection_yes}')
print(f'Total DeviceProtection no intert: {DeviceProtection_no_intert}')
print(f'Total DeviceProtection: {Total_DeviceProtection}')

Total DeviceProtection no: 3095
Total DeviceProtection yes: 2422
Total DeviceProtection no intert: 1526
Total DeviceProtection: 7043

# TechSupport

In [21]:
TechSupport_no = df["TechSupport"].value_counts()[0]
TechSupport_yes = df["TechSupport"].value_counts()[1]
TechSupport_no_intert = df["TechSupport"].value_counts()[2]
total_TechSupport = df["TechSupport"].value_counts().sum()

print(f'Total TechSupport no: {TechSupport_no}')
print(f'Total TechSupport yes: {TechSupport_yes}')
print(f'Total TechSupport no intert: {TechSupport_no_intert}')
print(f'Total TechSupport: {total_TechSupport}')

Total TechSupport no: 3473
Total TechSupport yes: 2044
Total TechSupport no intert: 1526
Total TechSupport: 7043

# StreamingTV

In [22]:
StreamingTV_no = df["StreamingTV"].value_counts()[0]
StreamingTV_yes = df["StreamingTV"].value_counts()[1]
StreamingTV_no_intert = df["StreamingTV"].value_counts()[2]

print(f'Total StreamingTV no: {StreamingTV_no}')
print(f'Total StreamingTV yes: {StreamingTV_yes}')
print(f'Total StreamingTV no intert: {StreamingTV_no_intert}')

Total StreamingTV no: 2810
Total StreamingTV yes: 2707
Total StreamingTV no intert: 1526

# StreamingMovies

In [23]:
StreamingTV_no = df["StreamingTV"].value_counts()[0]
StreamingTV_yes = df["StreamingTV"].value_counts()[1]
StreamingTV_no_intert = df["StreamingTV"].value_counts()[2]
StreamingTV_all = df["StreamingTV"].value_counts().sum()

print(f'Total StreamingTV no: {StreamingTV_no}')
print(f'Total StreamingTV yes: {StreamingTV_yes}')
print(f'Total StreamingTV no intert: {StreamingTV_no_intert}')
print(f'Total StreamingTV: {StreamingTV_all}')

Total StreamingTV no: 2810
Total StreamingTV yes: 2707
Total StreamingTV no intert: 1526
Total StreamingTV: 7043

# Contract

In [24]:
Contract_Monthly = df["Contract"].value_counts()[0]
Contract_2_year = df["Contract"].value_counts()[1]
Contract_1_year = df["Contract"].value_counts()[2]
Contract_all = df["Contract"].value_counts().sum()

print(f'Total Contract Monthly: {Contract_Monthly}')
print(f'Total Contract 2 year: {Contract_2_year}')
print(f'Total Contract 1 year {StreamingTV_no_intert}')
print(f'Total  {Contract_all}')

Total Contract Monthly: 3875
Total Contract 2 year: 1695
Total Contract 1 year 1526
Total  7043

# PaperlessBilling

In [25]:
PaperlessBilling_yes = df["PaperlessBilling"].value_counts()[0]
PaperlessBilling_no = df["PaperlessBilling"].value_counts()[1]
total_PaperlessBilling = df["PaperlessBilling"].value_counts().sum()

print(f'Total PaperlessBilling Yes: {PaperlessBilling_yes}')
print(f'Total PaperlessBilling No: {PaperlessBilling_no}')
print(f'Total PaperlessBilling: {total_PaperlessBilling}')

Total PaperlessBilling Yes: 4171
Total PaperlessBilling No: 2872
Total PaperlessBilling: 7043

# PaymentMethod

In [26]:
PaymentMethod_electronic = df["PaymentMethod"].value_counts()[0]
PaymentMethod_mail = df["PaymentMethod"].value_counts()[1]
PaymentMethod_bank = df["PaymentMethod"].value_counts()[2]
PaymentMethod_credit_card = df["PaymentMethod"].value_counts()[3]
PaymentMethod_all = df["Contract"].value_counts().sum()

print(f'Total PaymentMethod Electronic check: {PaymentMethod_electronic}')
print(f'Total PaymentMethod Mailed check: {PaymentMethod_mail}')
print(f'Total PaymentMethod Bank transfer (automatic): {PaymentMethod_bank}')
print(f'Total PaymentMethod Credit card (automatic): {PaymentMethod_credit_card}')
print(f'Total  {PaymentMethod_all}')

Total PaymentMethod Electronic check: 2365
Total PaymentMethod Mailed check: 1612
Total PaymentMethod Bank transfer (automatic): 1544
Total PaymentMethod Credit card (automatic): 1522
Total  7043

In [46]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [27]:
sorted(df["MonthlyCharges"].unique().tolist())

[18.25,
 18.4,
 18.55,
 18.7,
 18.75,
 18.8,
 18.85,
 18.9,
 18.95,
 19.0,
 19.05,
 19.1,
 19.15,
 19.2,
 19.25,
 19.3,
 19.35,
 19.4,
 19.45,
 19.5,
 19.55,
 19.6,
 19.65,
 19.7,
 19.75,
 19.8,
 19.85,
 19.9,
 19.95,
 20.0,
 20.05,
 20.1,
 20.15,
 20.2,
 20.25,
 20.3,
 20.35,
 20.4,
 20.45,
 20.5,
 20.55,
 20.6,
 20.65,
 20.7,
 20.75,
 20.8,
 20.85,
 20.9,
 20.95,
 21.0,
 21.05,
 21.1,
 21.15,
 21.2,
 21.25,
 21.3,
 21.45,
 22.95,
 23.05,
 23.15,
 23.3,
 23.4,
 23.45,
 23.5,
 23.55,
 23.6,
 23.65,
 23.75,
 23.8,
 23.85,
 23.9,
 23.95,
 24.0,
 24.05,
 24.1,
 24.15,
 24.2,
 24.25,
 24.3,
 24.35,
 24.4,
 24.45,
 24.5,
 24.55,
 24.6,
 24.65,
 24.7,
 24.75,
 24.8,
 24.85,
 24.9,
 24.95,
 25.0,
 25.05,
 25.1,
 25.15,
 25.2,
 25.25,
 25.3,
 25.35,
 25.4,
 25.45,
 25.5,
 25.55,
 25.6,
 25.65,
 25.7,
 25.75,
 25.8,
 25.85,
 25.9,
 25.95,
 26.0,
 26.05,
 26.1,
 26.2,
 26.25,
 26.3,
 26.35,
 26.4,
 26.45,
 26.5,
 26.8,
 26.9,
 28.45,
 28.5,
 28.6,
 29.05,
 29.1,
 29.15,
 29.2,
 29.25,
 29.3,
 29.35,
 29.4,
 29.45,
 29.5,
 29.6,
 29.65,
 29.7,
 29.75,
 29.8,
 29.85,
 29.9,
 29.95,
 30.05,
 30.1,
 30.15,
 30.2,
 30.25,
 30.3,
 30.35,
 30.4,
 30.45,
 30.5,
 30.55,
 30.6,
 30.75,
 30.85,
 30.9,
 31.0,
 31.05,
 31.1,
 31.2,
 31.35,
 31.65,
 33.15,
 33.45,
 33.5,
 33.55,
 33.6,
 33.65,
 33.7,
 33.75,
 33.9,
 34.0,
 34.05,
 34.2,
 34.25,
 34.3,
 34.4,
 34.5,
 34.55,
 34.6,
 34.65,
 34.7,
 34.8,
 34.85,
 34.95,
 35.0,
 35.05,
 35.1,
 35.15,
 35.2,
 35.25,
 35.3,
 35.35,
 35.4,
 35.45,
 35.5,
 35.55,
 35.6,
 35.65,
 35.7,
 35.75,
 35.8,
 35.9,
 36.0,
 36.05,
 36.1,
 36.15,
 36.25,
 36.45,
 36.5,
 36.65,
 36.85,
 37.7,
 38.1,
 38.25,
 38.5,
 38.55,
 38.6,
 38.8,
 38.85,
 38.9,
 39.0,
 39.05,
 39.1,
 39.15,
 39.2,
 39.3,
 39.35,
 39.4,
 39.45,
 39.5,
 39.55,
 39.6,
 39.65,
 39.7,
 39.85,
 39.9,
 39.95,
 40.0,
 40.05,
 40.1,
 40.15,
 40.2,
 40.25,
 40.3,
 40.35,
 40.4,
 40.45,
 40.55,
 40.6,
 40.65,
 40.7,
 40.75,
 40.9,
 41.05,
 41.1,
 41.15,
 41.35,
 41.6,
 41.9,
 41.95,
 42.1,
 42.3,
 42.35,
 42.4,
 42.6,
 42.9,
 43.05,
 43.25,
 43.3,
 43.35,
 43.45,
 43.55,
 43.6,
 43.65,
 43.7,
 43.75,
 43.8,
 43.85,
 43.9,
 43.95,
 44.0,
 44.05,
 44.1,
 44.15,
 44.2,
 44.25,
 44.3,
 44.35,
 44.4,
 44.45,
 44.5,
 44.55,
 44.6,
 44.65,
 44.7,
 44.75,
 44.8,
 44.85,
 44.9,
 44.95,
 45.0,
 45.05,
 45.1,
 45.15,
 45.2,
 45.25,
 45.3,
 45.35,
 45.4,
 45.45,
 45.5,
 45.55,
 45.6,
 45.65,
 45.7,
 45.75,
 45.8,
 45.85,
 45.9,
 45.95,
 46.0,
 46.05,
 46.1,
 46.2,
 46.25,
 46.3,
 46.35,
 46.4,
 46.6,
 47.05,
 47.15,
 47.4,
 47.6,
 47.8,
 47.85,
 47.95,
 48.15,
 48.2,
 48.25,
 48.35,
 48.4,
 48.45,
 48.55,
 48.6,
 48.65,
 48.7,
 48.75,
 48.8,
 48.85,
 48.9,
 48.95,
 49.0,
 49.05,
 49.1,
 49.15,
 49.2,
 49.25,
 49.3,
 49.35,
 49.4,
 49.45,
 49.5,
 49.55,
 49.6,
 49.65,
 49.7,
 49.75,
 49.8,
 49.85,
 49.9,
 49.95,
 50.0,
 50.05,
 50.1,
 50.15,
 50.2,
 50.25,
 50.3,
 50.35,
 50.4,
 50.45,
 50.5,
 50.55,
 50.6,
 50.65,
 50.7,
 50.75,
 50.8,
 50.85,
 50.9,
 50.95,
 51.0,
 51.05,
 51.1,
 51.15,
 51.2,
 51.25,
 51.3,
 51.35,
 51.4,
 51.45,
 51.5,
 51.55,
 51.6,
 51.65,
 51.7,
 51.75,
 51.8,
 52.0,
 52.1,
 52.15,
 52.2,
 52.3,
 52.5,
 52.55,
 52.7,
 52.85,
 53.0,
 53.1,
 53.15,
 53.3,
 53.35,
 53.4,
 53.45,
 53.5,
 53.55,
 53.6,
 53.65,
 53.7,
 53.75,
 53.8,
 53.85,
 53.9,
 53.95,
 54.0,
 54.05,
 54.1,
 54.15,
 54.2,
 54.25,
 54.3,
 54.35,
 54.4,
 54.45,
 54.5,
 54.55,
 54.6,
 54.65,
 54.7,
 54.75,
 54.8,
 54.85,
 54.9,
 54.95,
 55.0,
 55.05,
 55.1,
 55.15,
 55.2,
 55.25,
 55.3,
 55.35,
 55.4,
 55.45,
 55.5,
 55.55,
 55.6,
 55.65,
 55.7,
 55.75,
 55.8,
 55.85,
 55.9,
 55.95,
 56.0,
 56.05,
 56.1,
 56.15,
 56.2,
 56.25,
 56.3,
 56.35,
 56.4,
 56.45,
 56.5,
 56.55,
 56.6,
 56.65,
 56.7,
 56.75,
 56.8,
 56.85,
 56.9,
 56.95,
 57.15,
 57.2,
 57.45,
 57.5,
 57.55,
 57.6,
 57.65,
 57.75,
 57.8,
 57.95,
 58.0,
 58.2,
 58.25,
 58.35,
 58.4,
 58.45,
 58.5,
 58.55,
 58.6,
 58.65,
 58.7,
 58.75,
 58.85,
 58.9,
 58.95,
 59.0,
 59.05,
 59.1,
 59.15,
 59.2,
 59.25,
 59.3,
 59.4,
 59.45,
 59.5,
 59.55,
 59.6,
 59.65,
 59.7,
 59.75,
 59.8,
 59.85,
 59.9,
 59.95,
 60.0,
 60.05,
 60.1,
 60.15,
 60.2,
 60.25,
 60.3,
 60.35,
 60.4,
 60.45,
 60.5,
 60.55,
 60.6,
 60.65,
 60.7,
 60.75,
 60.8,
 60.85,
 60.9,
 60.95,
 61.0,
 61.05,
 61.1,
 61.15,
 61.2,
 61.25,
 61.3,
 61.35,
 61.4,
 61.45,
 61.5,
 61.55,
 61.6,
 61.65,
 61.75,
 61.8,
 61.9,
 61.95,
 62.05,
 62.1,
 62.15,
 62.25,
 62.3,
 62.45,
 62.5,
 62.55,
 62.65,
 62.7,
 62.8,
 62.85,
 63.05,
 63.1,
 63.15,
 63.25,
 63.3,
 63.35,
 63.4,
 63.55,
 63.6,
 63.7,
 63.75,
 63.8,
 63.85,
 63.9,
 63.95,
 64.0,
 64.05,
 64.1,
 64.15,
 64.2,
 64.25,
 64.3,
 64.35,
 64.4,
 64.45,
 64.5,
 64.55,
 64.6,
 64.65,
 64.7,
 64.75,
 64.8,
 64.85,
 64.9,
 64.95,
 65.0,
 65.05,
 65.1,
 65.15,
 65.2,
 65.25,
 65.3,
 65.35,
 65.4,
 65.45,
 65.5,
 65.55,
 65.6,
 65.65,
 65.7,
 65.75,
 65.8,
 65.85,
 65.9,
 66.0,
 66.05,
 66.1,
 66.15,
 66.2,
 66.25,
 66.3,
 66.35,
 66.4,
 66.5,
 66.6,
 66.65,
 66.7,
 66.75,
 66.8,
 66.85,
 66.9,
 67.05,
 67.2,
 67.25,
 67.4,
 67.45,
 67.5,
 67.6,
 67.65,
 67.7,
 67.75,
 67.8,
 67.85,
 67.95,
 68.05,
 68.1,
 68.15,
 68.25,
 68.3,
 68.35,
 68.4,
 68.45,
 68.5,
 68.55,
 68.6,
 68.65,
 68.7,
 68.75,
 68.8,
 68.85,
 68.9,
 68.95,
 69.0,
 69.05,
 69.1,
 69.15,
 69.2,
 69.25,
 69.3,
 69.35,
 69.4,
 69.45,
 69.5,
 69.55,
 69.6,
 69.65,
 69.7,
 69.75,
 69.8,
 69.85,
 69.9,
 69.95,
 70.0,
 70.05,
 70.1,
 70.15,
 70.2,
 70.25,
 70.3,
 70.35,
 70.4,
 70.45,
 70.5,
 70.55,
 70.6,
 70.65,
 70.7,
 70.75,
 70.8,
 70.85,
 70.9,
 70.95,
 71.0,
 71.05,
 71.1,
 71.15,
 71.25,
 71.3,
 71.35,
 71.4,
 71.45,
 71.5,
 71.55,
 71.6,
 71.65,
 71.7,
 71.75,
 71.8,
 71.85,
 71.9,
 71.95,
 72.0,
 72.1,
 72.15,
 72.2,
 72.25,
 72.35,
 72.45,
 72.6,
 72.65,
 72.75,
 72.8,
 72.85,
 72.9,
 72.95,
 73.0,
 73.05,
 73.1,
 73.15,
 73.2,
 73.25,
 73.3,
 73.35,
 73.45,
 73.5,
 73.55,
 73.6,
 73.65,
 73.7,
 73.75,
 73.8,
 73.85,
 73.9,
 73.95,
 74.0,
 74.05,
 74.1,
 74.15,
 74.2,
 74.25,
 74.3,
 74.35,
 74.4,
 74.45,
 74.5,
 74.55,
 74.6,
 74.65,
 74.7,
 74.75,
 74.8,
 74.85,
 74.9,
 74.95,
 75.0,
 75.05,
 75.1,
 75.15,
 75.2,
 75.25,
 75.3,
 75.35,
 75.4,
 75.45,
 75.5,
 75.55,
 75.6,
 75.65,
 75.7,
 75.75,
 75.8,
 75.85,
 75.9,
 75.95,
 76.0,
 76.05,
 76.1,
 76.15,
 76.2,
 76.25,
 76.3,
 76.35,
 76.4,
 76.45,
 76.5,
 76.55,
 76.6,
 76.65,
 76.75,
 76.8,
 76.85,
 76.9,
 76.95,
 77.0,
 77.15,
 77.2,
 77.3,
 77.35,
 77.4,
 77.5,
 77.55,
 77.65,
 77.75,
 77.8,
 77.85,
 77.9,
 77.95,
 78.0,
 78.05,
 78.1,
 78.15,
 78.2,
 78.25,
 78.3,
 78.35,
 78.4,
 78.45,
 78.5,
 78.55,
 78.6,
 78.65,
 78.7,
 78.75,
 78.8,
 78.85,
 78.9,
 78.95,
 79.0,
 79.05,
 79.1,
 79.15,
 79.2,
 79.25,
 79.3,
 79.35,
 79.4,
 79.45,
 79.5,
 79.55,
 79.6,
 79.65,
 79.7,
 79.75,
 79.8,
 79.85,
 79.9,
 79.95,
 80.0,
 80.05,
 80.1,
 80.15,
 80.2,
 80.25,
 80.3,
 80.35,
 80.4,
 80.45,
 80.5,
 80.55,
 80.6,
 80.65,
 80.7,
 80.75,
 80.8,
 80.85,
 80.9,
 80.95,
 81.0,
 81.05,
 81.1,
 81.15,
 81.2,
 81.25,
 81.3,
 81.35,
 81.4,
 81.45,
 81.5,
 81.55,
 81.6,
 81.65,
 81.7,
 81.75,
 81.8,
 81.85,
 81.9,
 81.95,
 82.0,
 82.05,
 82.1,
 82.15,
 82.3,
 82.35,
 82.4,
 82.45,
 82.5,
 82.55,
 82.65,
 82.7,
 82.75,
 82.85,
 82.9,
 82.95,
 83.0,
 83.05,
 83.15,
 83.2,
 83.25,
 83.3,
 83.35,
 83.4,
 83.45,
 83.5,
 83.55,
 83.6,
 83.65,
 83.7,
 83.75,
 83.8,
 83.85,
 83.9,
 83.95,
 84.0,
 84.05,
 84.1,
 84.15,
 84.2,
 84.25,
 84.3,
 84.35,
 84.4,
 84.45,
 84.5,
 84.55,
 84.6,
 84.65,
 84.7,
 84.75,
 84.8,
 84.85,
 84.9,
 84.95,
 85.0,
 85.05,
 85.1,
 85.15,
 85.2,
 ...]

In [28]:
min_MonthlyCharges = df["MonthlyCharges"].min(); max_MonthlyCharges= df["MonthlyCharges"].max()

min_MonthlyCharges, 
print(f'min MonthlyCharges {min_MonthlyCharges}')
print(f'max MonthlyCharges {max_MonthlyCharges}')

min MonthlyCharges 18.25
max MonthlyCharges 118.75

# TotalCharges

In [29]:
TotalCharges_male = df["TotalCharges"][df["gender"] == 'Male'].value_counts().sum()
TotalCharges_female = df["TotalCharges"][df["gender"] == 'Female'].value_counts().sum()
TotalCharges = df["TotalCharges"].value_counts().sum()

print(f'TotalCharges male {TotalCharges_male}')
print(f'TotalCharges female  {TotalCharges_female}')
print(f'TotalCharges  {TotalCharges}')

TotalCharges male 3555
TotalCharges female  3488
TotalCharges  7043

In [30]:
df.sample(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3068,1810-BOHSY,Male,0,Yes,No,51,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,One year,Yes,Credit card (automatic),96.4,4911.05,No
1362,2568-BRGYX,Male,0,No,No,4,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.2,237.95,Yes

In [31]:
df["Churn"].value_counts().sum()

np.int64(7043)

# Churn = Kündigung: Male, Female, Total

In [32]:
Churn_male = df["Churn"][df["gender"] == 'Male'].value_counts().sum()
Churn_female = df["Churn"][df["gender"] == 'Female'].value_counts().sum()
Total_Churn = df["Churn"].value_counts().sum()

print(f'Total Churn male: {Churn_male}')
print(f'Total Churn female: {Churn_female}')
print(f'Total Churn: {Total_Churn}')

Total Churn male: 3555
Total Churn female: 3488
Total Churn: 7043

In [47]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

# Churn: No, Yes, Total

In [33]:
Churn_no = df["Churn"].value_counts()[0]
Churn_yes = df["Churn"].value_counts()[1]
Churn_all = df["Churn"].value_counts().sum()

print(f'Total Churn No: {Churn_no}')
print(f'Total Churn Yes: {Churn_yes}')
print(f'Total Churn: {Churn_all}')

Total Churn No: 5174
Total Churn Yes: 1869
Total Churn: 7043

In [34]:
df.to_csv('../data/cleanded data/Data_1_Telco-Customer-Churn.csv')