In [16]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder

In [17]:
os.listdir('../data/raw')

['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [18]:
df = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

Encoding Categorical Cloumns

In [19]:
df.sample()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2933,5220-AGAAX,Male,0,Yes,Yes,68,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),24.0,1664.3,No

In [20]:
df.drop( 'customerID', axis=1, inplace= True)

In [21]:
df['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [22]:
def encode_contract_time( df ):
    df['Contract'] = df['Contract'].map({
       'Month-to-month': 0, 'One year': 1, 'Two year': 2
    })
    return df

df = encode_contract_time (df )

In [23]:
df['Contract'].value_counts()

Contract
0    3875
2    1695
1    1473
Name: count, dtype: int64

# Churn from Yes, No to --> 1, 0

In [24]:
# Das Ziel (y) in Zahlen umwandeln (Löst den pos_label Fehler)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [25]:
df.sample()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1831,Female,1,Yes,No,22,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,0,Yes,Mailed check,63.55,1381.8,0

In [26]:
df.to_csv('../data/preprocessing data/preprocessing_data.csv', index =  False)